// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc_stream.proto

package grpcstream

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetNamesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNamesRequest) Reset()         { *m = GetNamesRequest{} }
func (m *GetNamesRequest) String() string { return proto.CompactTextString(m) }
func (*GetNamesRequest) ProtoMessage()    {}
func (*GetNamesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d860590ebf11e2c, []int{0}
}

func (m *GetNamesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNamesRequest.Unmarshal(m, b)
}
func (m *GetNamesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNamesRequest.Marshal(b, m, deterministic)
}
func (m *GetNamesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNamesRequest.Merge(m, src)
}
func (m *GetNamesRequest) XXX_Size() int {
	return xxx_messageInfo_GetNamesRequest.Size(m)
}
func (m *GetNamesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNamesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNamesRequest proto.InternalMessageInfo

type GetNamesResponse struct {
	Names                []*Name  `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNamesResponse) Reset()         { *m = GetNamesResponse{} }
func (m *GetNamesResponse) String() string { return proto.CompactTextString(m) }
func (*GetNamesResponse) ProtoMessage()    {}
func (*GetNamesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d860590ebf11e2c, []int{1}
}

func (m *GetNamesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNamesResponse.Unmarshal(m, b)
}
func (m *GetNamesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNamesResponse.Marshal(b, m, deterministic)
}
func (m *GetNamesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNamesResponse.Merge(m, src)
}
func (m *GetNamesResponse) XXX_Size() int {
	return xxx_messageInfo_GetNamesResponse.Size(m)
}
func (m *GetNamesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNamesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNamesResponse proto.InternalMessageInfo

func (m *GetNamesResponse) GetNames() []*Name {
	if m != nil {
		return m.Names
	}
	return nil
}

type ListSkillsRequest struct {
	Name                 *Name    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSkillsRequest) Reset()         { *m = ListSkillsRequest{} }
func (m *ListSkillsRequest) String() string { return proto.CompactTextString(m) }
func (*ListSkillsRequest) ProtoMessage()    {}
func (*ListSkillsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d860590ebf11e2c, []int{2}
}

func (m *ListSkillsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSkillsRequest.Unmarshal(m, b)
}
func (m *ListSkillsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSkillsRequest.Marshal(b, m, deterministic)
}
func (m *ListSkillsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSkillsRequest.Merge(m, src)
}
func (m *ListSkillsRequest) XXX_Size() int {
	return xxx_messageInfo_ListSkillsRequest.Size(m)
}
func (m *ListSkillsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSkillsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSkillsRequest proto.InternalMessageInfo

func (m *ListSkillsRequest) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

type ListSkillsResponse struct {
	Name                 *Name    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Skill                *Skill   `protobuf:"bytes,2,opt,name=skill,proto3" json:"skill,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSkillsResponse) Reset()         { *m = ListSkillsResponse{} }
func (m *ListSkillsResponse) String() string { return proto.CompactTextString(m) }
func (*ListSkillsResponse) ProtoMessage()    {}
func (*ListSkillsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d860590ebf11e2c, []int{3}
}

func (m *ListSkillsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSkillsResponse.Unmarshal(m, b)
}
func (m *ListSkillsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSkillsResponse.Marshal(b, m, deterministic)
}
func (m *ListSkillsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSkillsResponse.Merge(m, src)
}
func (m *ListSkillsResponse) XXX_Size() int {
	return xxx_messageInfo_ListSkillsResponse.Size(m)
}
func (m *ListSkillsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSkillsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSkillsResponse proto.InternalMessageInfo

func (m *ListSkillsResponse) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ListSkillsResponse) GetSkill() *Skill {
	if m != nil {
		return m.Skill
	}
	return nil
}

type Name struct {
	FullName             string   `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d860590ebf11e2c, []int{4}
}

func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (m *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(m, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

type Skill struct {
	Language             string   `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	ExpYears             int32    `protobuf:"varint,2,opt,name=exp_years,json=expYears,proto3" json:"exp_years,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Skill) Reset()         { *m = Skill{} }
func (m *Skill) String() string { return proto.CompactTextString(m) }
func (*Skill) ProtoMessage()    {}
func (*Skill) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d860590ebf11e2c, []int{5}
}

func (m *Skill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Skill.Unmarshal(m, b)
}
func (m *Skill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Skill.Marshal(b, m, deterministic)
}
func (m *Skill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Skill.Merge(m, src)
}
func (m *Skill) XXX_Size() int {
	return xxx_messageInfo_Skill.Size(m)
}
func (m *Skill) XXX_DiscardUnknown() {
	xxx_messageInfo_Skill.DiscardUnknown(m)
}

var xxx_messageInfo_Skill proto.InternalMessageInfo

func (m *Skill) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Skill) GetExpYears() int32 {
	if m != nil {
		return m.ExpYears
	}
	return 0
}

func init() {
	proto.RegisterType((*GetNamesRequest)(nil), "grpcstream.GetNamesRequest")
	proto.RegisterType((*GetNamesResponse)(nil), "grpcstream.GetNamesResponse")
	proto.RegisterType((*ListSkillsRequest)(nil), "grpcstream.ListSkillsRequest")
	proto.RegisterType((*ListSkillsResponse)(nil), "grpcstream.ListSkillsResponse")
	proto.RegisterType((*Name)(nil), "grpcstream.Name")
	proto.RegisterType((*Skill)(nil), "grpcstream.Skill")
}

func init() { proto.RegisterFile("grpc_stream.proto", fileDescriptor_5d860590ebf11e2c) }

var fileDescriptor_5d860590ebf11e2c = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4b, 0xc3, 0x30,
	0x18, 0xc5, 0xad, 0xae, 0xd2, 0x7d, 0x1e, 0x5c, 0xbf, 0x53, 0xe9, 0x54, 0x46, 0x14, 0xf5, 0x54,
	0x64, 0x9e, 0xf4, 0xe4, 0xad, 0x17, 0x51, 0xe8, 0x4e, 0x9e, 0x4a, 0x2c, 0xb1, 0x0c, 0xb3, 0x36,
	0x26, 0x29, 0xcc, 0x7f, 0xc8, 0xbf, 0x53, 0xbe, 0xd4, 0xae, 0x45, 0x27, 0xec, 0x98, 0xf7, 0x7b,
	0xef, 0x25, 0x3c, 0x02, 0x61, 0xa9, 0x55, 0x91, 0x1b, 0xab, 0x05, 0x5f, 0x25, 0x4a, 0xd7, 0xb6,
	0x46, 0x20, 0xa9, 0x55, 0x58, 0x08, 0xc7, 0xa9, 0xb0, 0x4f, 0x7c, 0x25, 0x4c, 0x26, 0x3e, 0x1a,
	0x61, 0x2c, 0xbb, 0x87, 0x49, 0x2f, 0x19, 0x55, 0x57, 0x46, 0xe0, 0x25, 0xf8, 0x15, 0x09, 0x91,
	0x37, 0x3b, 0xb8, 0x3e, 0x9a, 0x4f, 0x92, 0xbe, 0x22, 0x21, 0x67, 0xd6, 0x62, 0x76, 0x07, 0xe1,
	0xe3, 0xd2, 0xd8, 0xc5, 0xfb, 0x52, 0xca, 0xae, 0x10, 0x2f, 0x60, 0x44, 0x34, 0xf2, 0x66, 0xde,
	0xd6, 0xac, 0xa3, 0xac, 0x00, 0x1c, 0x46, 0x7f, 0x2e, 0xde, 0x29, 0x8b, 0x57, 0xe0, 0x1b, 0xca,
	0x45, 0xfb, 0xce, 0x16, 0x0e, 0x6d, 0xae, 0x30, 0x6b, 0x39, 0x3b, 0x87, 0x11, 0xc5, 0x70, 0x0a,
	0xe3, 0xb7, 0x46, 0xca, 0x7c, 0xd3, 0x3d, 0xce, 0x02, 0x12, 0x08, 0xb2, 0x07, 0xf0, 0x5d, 0x08,
	0x63, 0x08, 0x24, 0xaf, 0xca, 0x86, 0x97, 0x1b, 0x53, 0x77, 0xa6, 0x06, 0xb1, 0x56, 0xf9, 0xa7,
	0xe0, 0xda, 0xb8, 0x6b, 0xfd, 0x2c, 0x10, 0x6b, 0xf5, 0x42, 0xe7, 0xf9, 0x97, 0x07, 0x90, 0x6a,
	0x55, 0x2c, 0xdc, 0x13, 0x30, 0x85, 0xa0, 0x5b, 0x14, 0xa7, 0xc3, 0xb7, 0xfd, 0x9a, 0x3e, 0x3e,
	0xd9, 0x0e, 0xdb, 0x2d, 0xd8, 0x1e, 0x3e, 0x03, 0xf4, 0x1b, 0xe1, 0xe9, 0xd0, 0xfd, 0x67, 0xf6,
	0xf8, 0xec, 0x3f, 0xdc, 0xd5, 0xdd, 0x78, 0xaf, 0x87, 0xee, 0x47, 0xdc, 0x7e, 0x07, 0x00, 0x00,
	0xff, 0xff, 0xd3, 0x5d, 0x14, 0xdf, 0x26, 0x02, 0x00, 0x00,
}
