// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/grpc_stream.proto

package grpcstream

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetNamesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNamesRequest) Reset()         { *m = GetNamesRequest{} }
func (m *GetNamesRequest) String() string { return proto.CompactTextString(m) }
func (*GetNamesRequest) ProtoMessage()    {}
func (*GetNamesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ccdf62e339ae9eb, []int{0}
}

func (m *GetNamesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNamesRequest.Unmarshal(m, b)
}
func (m *GetNamesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNamesRequest.Marshal(b, m, deterministic)
}
func (m *GetNamesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNamesRequest.Merge(m, src)
}
func (m *GetNamesRequest) XXX_Size() int {
	return xxx_messageInfo_GetNamesRequest.Size(m)
}
func (m *GetNamesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNamesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNamesRequest proto.InternalMessageInfo

type GetNamesResponse struct {
	Names                []*Name  `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNamesResponse) Reset()         { *m = GetNamesResponse{} }
func (m *GetNamesResponse) String() string { return proto.CompactTextString(m) }
func (*GetNamesResponse) ProtoMessage()    {}
func (*GetNamesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ccdf62e339ae9eb, []int{1}
}

func (m *GetNamesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNamesResponse.Unmarshal(m, b)
}
func (m *GetNamesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNamesResponse.Marshal(b, m, deterministic)
}
func (m *GetNamesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNamesResponse.Merge(m, src)
}
func (m *GetNamesResponse) XXX_Size() int {
	return xxx_messageInfo_GetNamesResponse.Size(m)
}
func (m *GetNamesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNamesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNamesResponse proto.InternalMessageInfo

func (m *GetNamesResponse) GetNames() []*Name {
	if m != nil {
		return m.Names
	}
	return nil
}

type ListSkillsRequest struct {
	Name                 *Name    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSkillsRequest) Reset()         { *m = ListSkillsRequest{} }
func (m *ListSkillsRequest) String() string { return proto.CompactTextString(m) }
func (*ListSkillsRequest) ProtoMessage()    {}
func (*ListSkillsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ccdf62e339ae9eb, []int{2}
}

func (m *ListSkillsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSkillsRequest.Unmarshal(m, b)
}
func (m *ListSkillsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSkillsRequest.Marshal(b, m, deterministic)
}
func (m *ListSkillsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSkillsRequest.Merge(m, src)
}
func (m *ListSkillsRequest) XXX_Size() int {
	return xxx_messageInfo_ListSkillsRequest.Size(m)
}
func (m *ListSkillsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSkillsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSkillsRequest proto.InternalMessageInfo

func (m *ListSkillsRequest) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

type ListSkillsResponse struct {
	Name                 *Name    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Skill                *Skill   `protobuf:"bytes,2,opt,name=skill,proto3" json:"skill,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSkillsResponse) Reset()         { *m = ListSkillsResponse{} }
func (m *ListSkillsResponse) String() string { return proto.CompactTextString(m) }
func (*ListSkillsResponse) ProtoMessage()    {}
func (*ListSkillsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ccdf62e339ae9eb, []int{3}
}

func (m *ListSkillsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSkillsResponse.Unmarshal(m, b)
}
func (m *ListSkillsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSkillsResponse.Marshal(b, m, deterministic)
}
func (m *ListSkillsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSkillsResponse.Merge(m, src)
}
func (m *ListSkillsResponse) XXX_Size() int {
	return xxx_messageInfo_ListSkillsResponse.Size(m)
}
func (m *ListSkillsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSkillsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSkillsResponse proto.InternalMessageInfo

func (m *ListSkillsResponse) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ListSkillsResponse) GetSkill() *Skill {
	if m != nil {
		return m.Skill
	}
	return nil
}

type Name struct {
	FullName             string   `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ccdf62e339ae9eb, []int{4}
}

func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (m *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(m, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

type Skill struct {
	Language             string   `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	ExpYears             int32    `protobuf:"varint,2,opt,name=exp_years,json=expYears,proto3" json:"exp_years,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Skill) Reset()         { *m = Skill{} }
func (m *Skill) String() string { return proto.CompactTextString(m) }
func (*Skill) ProtoMessage()    {}
func (*Skill) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ccdf62e339ae9eb, []int{5}
}

func (m *Skill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Skill.Unmarshal(m, b)
}
func (m *Skill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Skill.Marshal(b, m, deterministic)
}
func (m *Skill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Skill.Merge(m, src)
}
func (m *Skill) XXX_Size() int {
	return xxx_messageInfo_Skill.Size(m)
}
func (m *Skill) XXX_DiscardUnknown() {
	xxx_messageInfo_Skill.DiscardUnknown(m)
}

var xxx_messageInfo_Skill proto.InternalMessageInfo

func (m *Skill) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Skill) GetExpYears() int32 {
	if m != nil {
		return m.ExpYears
	}
	return 0
}

func init() {
	proto.RegisterType((*GetNamesRequest)(nil), "grpcstream.GetNamesRequest")
	proto.RegisterType((*GetNamesResponse)(nil), "grpcstream.GetNamesResponse")
	proto.RegisterType((*ListSkillsRequest)(nil), "grpcstream.ListSkillsRequest")
	proto.RegisterType((*ListSkillsResponse)(nil), "grpcstream.ListSkillsResponse")
	proto.RegisterType((*Name)(nil), "grpcstream.Name")
	proto.RegisterType((*Skill)(nil), "grpcstream.Skill")
}

func init() { proto.RegisterFile("protos/grpc_stream.proto", fileDescriptor_6ccdf62e339ae9eb) }

var fileDescriptor_6ccdf62e339ae9eb = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4b, 0xc3, 0x30,
	0x18, 0xc5, 0xad, 0xae, 0xd2, 0x7d, 0x1e, 0x5c, 0xbf, 0x53, 0xe9, 0x54, 0x46, 0x14, 0xf5, 0x54,
	0x65, 0x9e, 0xf4, 0xe4, 0xad, 0x17, 0x51, 0xe8, 0x4e, 0x9e, 0x4a, 0x2c, 0xb1, 0x0c, 0xb3, 0x36,
	0x26, 0x29, 0xcc, 0x7f, 0xc8, 0xbf, 0x53, 0xbe, 0xd4, 0xae, 0x45, 0x27, 0x78, 0xcc, 0xfb, 0xbd,
	0xf7, 0x12, 0x1e, 0x81, 0x48, 0xe9, 0xda, 0xd6, 0xe6, 0xaa, 0xd4, 0xaa, 0xc8, 0x8d, 0xd5, 0x82,
	0xaf, 0x12, 0x27, 0x21, 0x90, 0xd4, 0x2a, 0x2c, 0x84, 0xc3, 0x54, 0xd8, 0x47, 0xbe, 0x12, 0x26,
	0x13, 0xef, 0x8d, 0x30, 0x96, 0xdd, 0xc1, 0xa4, 0x97, 0x8c, 0xaa, 0x2b, 0x23, 0xf0, 0x1c, 0xfc,
	0x8a, 0x84, 0xc8, 0x9b, 0xed, 0x5d, 0x1e, 0xcc, 0x27, 0x49, 0x5f, 0x91, 0x90, 0x33, 0x6b, 0x31,
	0xbb, 0x85, 0xf0, 0x61, 0x69, 0xec, 0xe2, 0x6d, 0x29, 0x65, 0x57, 0x88, 0x67, 0x30, 0x22, 0x1a,
	0x79, 0x33, 0x6f, 0x6b, 0xd6, 0x51, 0x56, 0x00, 0x0e, 0xa3, 0xdf, 0x17, 0xff, 0x2b, 0x8b, 0x17,
	0xe0, 0x1b, 0xca, 0x45, 0xbb, 0xce, 0x16, 0x0e, 0x6d, 0xae, 0x30, 0x6b, 0x39, 0x3b, 0x85, 0x11,
	0xc5, 0x70, 0x0a, 0xe3, 0xd7, 0x46, 0xca, 0x7c, 0xd3, 0x3d, 0xce, 0x02, 0x12, 0x08, 0xb2, 0x7b,
	0xf0, 0x5d, 0x08, 0x63, 0x08, 0x24, 0xaf, 0xca, 0x86, 0x97, 0x1b, 0x53, 0x77, 0xa6, 0x06, 0xb1,
	0x56, 0xf9, 0x87, 0xe0, 0xda, 0xb8, 0x6b, 0xfd, 0x2c, 0x10, 0x6b, 0xf5, 0x4c, 0xe7, 0xf9, 0xa7,
	0x07, 0x90, 0x6a, 0x55, 0x2c, 0xdc, 0x13, 0x30, 0x85, 0xa0, 0x5b, 0x14, 0xa7, 0xc3, 0xb7, 0xfd,
	0x98, 0x3e, 0x3e, 0xda, 0x0e, 0xdb, 0x2d, 0xd8, 0x0e, 0x3e, 0x01, 0xf4, 0x1b, 0xe1, 0xf1, 0xd0,
	0xfd, 0x6b, 0xf6, 0xf8, 0xe4, 0x2f, 0xdc, 0xd5, 0x5d, 0x7b, 0x2f, 0xfb, 0xee, 0x47, 0xdc, 0x7c,
	0x05, 0x00, 0x00, 0xff, 0xff, 0x80, 0xb9, 0x7f, 0x2d, 0x2d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GrpcStreamClient is the client API for GrpcStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcStreamClient interface {
	GetNames(ctx context.Context, in *GetNamesRequest, opts ...grpc.CallOption) (*GetNamesResponse, error)
	ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (GrpcStream_ListSkillsClient, error)
}

type grpcStreamClient struct {
	cc *grpc.ClientConn
}

func NewGrpcStreamClient(cc *grpc.ClientConn) GrpcStreamClient {
	return &grpcStreamClient{cc}
}

func (c *grpcStreamClient) GetNames(ctx context.Context, in *GetNamesRequest, opts ...grpc.CallOption) (*GetNamesResponse, error) {
	out := new(GetNamesResponse)
	err := c.cc.Invoke(ctx, "/grpcstream.GrpcStream/GetNames", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcStreamClient) ListSkills(ctx context.Context, in *ListSkillsRequest, opts ...grpc.CallOption) (GrpcStream_ListSkillsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GrpcStream_serviceDesc.Streams[0], "/grpcstream.GrpcStream/ListSkills", opts...)
	if err != nil {
		return nil, err
	}
	x := &grpcStreamListSkillsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GrpcStream_ListSkillsClient interface {
	Recv() (*ListSkillsResponse, error)
	grpc.ClientStream
}

type grpcStreamListSkillsClient struct {
	grpc.ClientStream
}

func (x *grpcStreamListSkillsClient) Recv() (*ListSkillsResponse, error) {
	m := new(ListSkillsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GrpcStreamServer is the server API for GrpcStream service.
type GrpcStreamServer interface {
	GetNames(context.Context, *GetNamesRequest) (*GetNamesResponse, error)
	ListSkills(*ListSkillsRequest, GrpcStream_ListSkillsServer) error
}

// UnimplementedGrpcStreamServer can be embedded to have forward compatible implementations.
type UnimplementedGrpcStreamServer struct {
}

func (*UnimplementedGrpcStreamServer) GetNames(ctx context.Context, req *GetNamesRequest) (*GetNamesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNames not implemented")
}
func (*UnimplementedGrpcStreamServer) ListSkills(req *ListSkillsRequest, srv GrpcStream_ListSkillsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListSkills not implemented")
}

func RegisterGrpcStreamServer(s *grpc.Server, srv GrpcStreamServer) {
	s.RegisterService(&_GrpcStream_serviceDesc, srv)
}

func _GrpcStream_GetNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcStreamServer).GetNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcstream.GrpcStream/GetNames",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcStreamServer).GetNames(ctx, req.(*GetNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcStream_ListSkills_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListSkillsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GrpcStreamServer).ListSkills(m, &grpcStreamListSkillsServer{stream})
}

type GrpcStream_ListSkillsServer interface {
	Send(*ListSkillsResponse) error
	grpc.ServerStream
}

type grpcStreamListSkillsServer struct {
	grpc.ServerStream
}

func (x *grpcStreamListSkillsServer) Send(m *ListSkillsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _GrpcStream_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcstream.GrpcStream",
	HandlerType: (*GrpcStreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNames",
			Handler:    _GrpcStream_GetNames_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListSkills",
			Handler:       _GrpcStream_ListSkills_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protos/grpc_stream.proto",
}
